# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            '0xCAFEFACE'
tagline:          'Give me moar coffee!!1😠'
description:      'No recuero demasiado de lo que hice anoche... ¿qué fué?, ah! sí... estaba en un CTF cuando... Give me moar coffee!!1😠'
url:              http://spageek.github.io
baseurl:          /

author:
  name:           'JR.Lambea'
  url:            https://twitter.com/jr_lambea

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/spageek/spageek.github.io
