# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            0xCAFEFACE
tagline:          'Give me moar coffee!!1😠'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://spageek.github.io
baseurl:          /

author:
  name:           'JR.Lambea'
  url:            https://twitter.com/jr_lambea

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/spageek/spageek.github.io
